apiVersion: v2
name: kong-mesh
description: A Helm chart for Kubernetes Install Mesh Using init Container Method
type: application
version: 0.1.0


dependencies:
- name: kong-mesh
  version: "2.9.1"
  repository: https://kong.github.io/kong-mesh-charts