kuma:
  controlPlane:
    mode: zone
    zone: windows
    kdsGlobalAddress: grpcs://eu.mesh.sync.konghq.com:443
    konnect:
      cpId: b7d12b50-096d-4536-aad7-0983002b5e52
    secrets:
      - Env: KMESH_MULTIZONE_ZONE_KDS_AUTH_CP_TOKEN_INLINE
        Secret: cp-token
        Key: token

    podSecurityContext:
      runAsNonRoot: true

    containerSecurityContext:
      readOnlyRootFilesystem: true

  ingress:
    enabled: true
  egress:
    enabled: true