apiVersion: v1
kind: Secret
metadata:
  name: cp-token
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: c3BhdF9JSjRraXNSRVhvRGNXM0Z0UmNpdXRpcmdCSjBwU1JGQW9lTWdmcjF4bEpTd1BBRUZx #c3BhdF9mckJJckc2TWNteHpGVDVibEE3M053N1g2UDliOUNMbzNxUlZWZlhoMjMyQTBlTGVC